# Generated by Django 3.2.9 on 2022-04-01 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='S_Adhar_No',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_Dept',
            field=models.CharField(choices=[('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('CSE', 'CSE'), ('EEE', 'EEE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_Reg_No',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(max_length=100)),
                ('S_Attendance', models.IntegerField()),
                ('S_Percentage', models.IntegerField()),
                ('STD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_data_app.student')),
            ],
        ),
    ]
