# Generated by Django 3.2.9 on 2022-04-01 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_data_app', '0003_rename_s_name_studentstatus_s_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='STD',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='student_data_app.student'),
        ),
    ]
