# Generated by Django 3.2.9 on 2022-04-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_data_app', '0005_alter_studentstatus_std'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatus',
            old_name='STD',
            new_name='display',
        ),
    ]
