# Generated by Django 3.2.9 on 2022-04-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_data_app', '0006_rename_std_studentstatus_display'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentStatus',
        ),
    ]
