# Generated by Django 3.2.9 on 2022-04-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_data_app', '0007_delete_studentstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
