# Generated by Django 3.2.9 on 2022-04-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_data_app', '0008_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Reg_No', models.IntegerField()),
                ('S_Name', models.CharField(max_length=100)),
                ('S_DOB', models.DateField()),
                ('S_Gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=100, null=True)),
                ('S_Dept', models.CharField(choices=[('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('CSE', 'CSE'), ('EEE', 'EEE')], max_length=100, null=True)),
                ('S_Yr', models.CharField(max_length=100)),
                ('S_Adhar_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(max_length=100)),
                ('S_Attendance', models.IntegerField()),
                ('S_Percentage', models.IntegerField()),
                ('STD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='student_data_app.student')),
            ],
        ),
    ]
