# Generated by Django 3.2.9 on 2022-04-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_data_app', '0012_auto_20220403_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='STD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='student_data_app.student'),
        ),
    ]
