# Generated by Django 3.2.9 on 2022-04-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data_app', '0015_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
