# Generated by Django 3.2.9 on 2022-04-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data_app', '0017_auto_20220404_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='S_DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='S_Dept',
            field=models.CharField(choices=[('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('CSE', 'CSE'), ('EEE', 'EEE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='S_Gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='S_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='S_Reg_No',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='S_Yr',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='S_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_Adhar_No',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='S_Attendance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='S_Percentage',
            field=models.IntegerField(null=True),
        ),
    ]
