# Generated by Django 3.2.9 on 2022-04-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data_app', '0018_auto_20220404_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='S_Adhar_No',
        ),
        migrations.RemoveField(
            model_name='student',
            name='S_DOB',
        ),
        migrations.RemoveField(
            model_name='student',
            name='S_Dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='S_Gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='S_Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='S_Reg_No',
        ),
        migrations.RemoveField(
            model_name='student',
            name='S_Yr',
        ),
        migrations.RemoveField(
            model_name='studentstatus',
            name='STD',
        ),
        migrations.RemoveField(
            model_name='studentstatus',
            name='S_Attendance',
        ),
        migrations.RemoveField(
            model_name='studentstatus',
            name='S_Name',
        ),
        migrations.RemoveField(
            model_name='studentstatus',
            name='S_Percentage',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
