# Generated by Django 3.2.9 on 2022-04-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_data_app', '0022_auto_20220405_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('S_Reg_No', models.IntegerField(null=True)),
                ('S_Name', models.CharField(max_length=100, null=True)),
                ('S_DOB', models.DateField(null=True)),
                ('S_Gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=100, null=True)),
                ('S_Dept', models.CharField(choices=[('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('CSE', 'CSE'), ('EEE', 'EEE')], max_length=100, null=True)),
                ('S_Yr', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, null=True)),
                ('S_Adhar_No', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='useres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('passw', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(max_length=100, null=True)),
                ('S_Attendance', models.IntegerField(null=True)),
                ('S_Percentage', models.IntegerField(null=True)),
                ('STD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='student_data_app.student')),
            ],
        ),
    ]
