# Generated by Django 3.2.9 on 2022-04-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_data_app', '0023_student_studentstatus_useres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useres',
        ),
    ]
